- name: install prometheus node exporter
  hosts: localhost
  tags:
    - node-exporter
  pre_tasks:
    - file: path=/var/lib/node_exporter state=directory
    - file: path=/var/lib/node_exporter/textfile_collector state=directory mode=0777
    # can't use the 'apt' module because it requires python-apt...
    - command: apt-get install -y -qq python-apt
  vars:
    prometheus_node_exporter_config_flags:
      'collector.textfile.directory': '/var/lib/node_exporter/textfile_collector'
    prometheus_node_exporter_enabled_collectors: []
  roles:
    - ansible-prometheus-node-exporter

- name: install docker-oom-exporter
  hosts: localhost
  tags:
    - oom-exporter
  vars:
    docker_oom_exporter_version: 0.1.9
  tasks:
    - name: stop docker-oom-exporter
      service: name=docker-oom-exporter state=stopped
      ignore_errors: yes
    - name: fetch oom-exporter binary
      get_url: "url=https://github.com/vad/docker_oom_exporter/releases/download/{{ docker_oom_exporter_version }}/docker_oom_exporter-{{ docker_oom_exporter_version }}-linux-amd64 dest=/usr/local/bin/docker_oom_exporter mode=0555 force=yes"
    - name: install upstart service definition
      template: src=templates/docker-oom-exporter.conf.j2 dest=/etc/init/docker-oom-exporter.conf
    - name: start docker-oom-exporter
      service: name=docker-oom-exporter state=started

- name: install cadvisor
  hosts: localhost
  tags:
    - cadvisor
  tasks:
    - name: Check if docker is installed
      command: docker version
      ignore_errors: yes
      register: docker_check
    - name: Install upstart service definition
      template: src=templates/cadvisor.conf.j2 dest=/etc/init/cadvisor.conf
      when: docker_check.rc == 0
    - name: Start cadvisor
      service: name=cadvisor state=started
      when: docker_check.rc == 0
