- name: install prometheus node exporter
  hosts: localhost
  pre_tasks:
    - file: path=/var/lib/node_exporter state=directory
    - file: path=/var/lib/node_exporter/textfile_collector state=directory mode=0777
    # can't use the 'apt' module because it requires python-apt...
    - command: apt-get install -y -qq python-apt
  vars:
    prometheus_node_exporter_config_flags:
      'collector.textfile.directory': '/var/lib/node_exporter/textfile_collector'
    prometheus_node_exporter_enabled_collectors: []
  roles:
    - ansible-prometheus-node-exporter

- name: install
  hosts: localhost
  tasks:
    - template: src=templates/cadvisor.conf.j2 dest=/etc/init/cadvisor.conf
    - service: name=cadvisor state=started
